### ISSUE TITLE
下载文件提示403

### ISSUE THREAD

**Issue by pongfcnkl** [UallenQbit/PikPakWeb#1]
目前pikpak会校验请求ip和下载ip，如果两个ip不一致直接报403
希望可以把请求下载地址放在本地浏览器上，而不是用服务器请求
![截图_20240526183630](https://github.com/UallenQbit/PikPakWeb/assets/24273319/7b684bf1-6c56-48f8-856c-5395374dc538)

**Comment by fgr178707** [comment]
> 目前pikpak会校验请求ip和下载ip，如果两个ip不一致直接报403 希望可以把请求下载地址放在本地浏览器上，而不是用服务器请求 ![截图_20240526183630](https://private-user-images.githubusercontent.com/24273319/333872384-7b684bf1-6c56-48f8-856c-5395374dc538.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3OTEwNDMsIm5iZiI6MTcxNjc5MDc0MywicGF0aCI6Ii8yNDI3MzMxOS8zMzM4NzIzODQtN2I2ODRiZjEtNmM1Ni00OGY4LTg1NmMtNTM5NTM3NGRjNTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA2MTkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzMWZlNDAzZmM1YTA1ZDgxOTkxN2Y5N2UzYTMzZTIyNjFmMWIyMzVmZTE2ZWQ2NzAzZjI1NTllOWMxZWI0YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dqOgOwTz0KH-IfMKyvv4pue2fX4AHWvLQ5yRHbphOLI)

下载源码 用 PHPStudy 本地部署
