### ISSUE TITLE
[求助] 网页调用aria2 无法下载 三个模式我都试了

### ISSUE THREAD

**Issue by fgr178707** [UallenQbit/PikPakWeb#6]
下载服务器：官方直连 
提示:
`-> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403`

下载服务器：官方IP直连
提示:
`
 -> [SocketCore.cc:1019] errorCode=1 SSL/TLS handshake failure: Error: 接收到的消息异常，或格式不正确。(80090326)
`

下载服务器：CDN代理加速
提示:
`
  -> [SocketCore.cc:1019] errorCode=1 SSL/TLS handshake failure: Error: 远程主机强迫关闭了一个现有的连接。(2746)
`

我的 aria2 没走代理 我这个地区可以直连pikapk 下载服务器 (用官方客户端下载，网络跑满)

[aria2配置文件.txt](https://github.com/user-attachments/files/16329125/aria2.txt)
[完整日志.txt](https://github.com/user-attachments/files/16329126/default.txt)

**Comment by moohr** [comment]
duplicate of #1
